In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [2]:
df = pd.read_csv('7-cyber_attack_data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   src_packet_rate              1000 non-null   float64
 1   dst_packet_rate              1000 non-null   float64
 2   avg_payload_size             1000 non-null   float64
 3   connection_duration          1000 non-null   float64
 4   tcp_flag_count               1000 non-null   float64
 5   avg_interarrival_time        1000 non-null   float64
 6   failed_login_attempts        1000 non-null   float64
 7   unusual_port_activity_score  1000 non-null   float64
 8   session_entropy              1000 non-null   float64
 9   avg_response_delay           1000 non-null   float64
 10  attack_type                  1000 non-null   int64
dtypes: float64(10), int64(1)
memory usage: 86.1 KB

In [4]:
df.describe()

,src_packet_rate,dst_packet_rate,avg_payload_size,connection_duration,tcp_flag_count,avg_interarrival_time,failed_login_attempts,unusual_port_activity_score,session_entropy,avg_response_delay,attack_type
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.012296,0.239737,-0.031142,0.013329,0.008900,0.016681,0.026614,0.315347,-0.045636,0.179530,1.003000
std,1.406123,1.635646,0.989677,1.001178,1.000905,1.027824,1.022217,1.364824,1.472316,0.960834,0.817104
min,-4.267039,-7.960328,-3.718638,-3.250031,-3.288725,-3.178790,-3.057529,-4.045045,-5.869039,-4.409592,0.000000
25%,-1.007421,-0.871250,-0.657668,-0.672964,-0.654218,-0.697799,-0.653787,-0.712015,-1.074499,-0.591831,0.000000
50%,0.085888,0.296278,-0.008968,0.045505,-0.032894,0.014639,0.049283,0.567003,0.121580,0.248920,1.000000
75%,1.080743,1.518676,0.615381,0.678219,0.687831,0.703139,0.713809,1.235890,1.013049,0.983239,2.000000
max,3.874738,7.168331,3.206344,2.741943,3.477044,3.600187,3.357941,4.020627,4.986178,4.112542,2.000000

In [5]:
df.head()

,src_packet_rate,dst_packet_rate,avg_payload_size,connection_duration,tcp_flag_count,avg_interarrival_time,failed_login_attempts,unusual_port_activity_score,session_entropy,avg_response_delay,attack_type
0,-1.286132,-0.648334,1.044115,-0.469715,0.789859,-0.083727,-1.647309,-1.316412,1.011910,-0.898063,2
1,-0.222224,2.083232,1.191114,-1.354527,-0.956992,1.696028,-1.070406,0.981403,-1.628798,1.377594,0
2,-0.431963,0.375745,-1.370334,0.819214,0.345243,1.389447,-1.904130,1.292602,0.925545,0.232705,0
3,-0.912633,0.986988,-0.690042,2.014628,-0.442260,0.590347,-1.819353,1.560938,0.823755,0.517762,0
4,-0.367056,1.667892,0.879172,2.214276,1.846338,-0.894047,1.543838,0.931103,-1.015210,1.061845,1

In [6]:
X = df.drop('attack_type' , axis = 1) 
y = df['attack_type']

from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X , y , random_state = 15 , test_size = 0.3 )

from sklearn.linear_model import LogisticRegression 

logistic = LogisticRegression()
logistic.fit(X_train , y_train)

y_pred = logistic.predict(X_test)

In [7]:
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
score = accuracy_score(y_test , y_pred) 
classification = classification_report(y_test , y_pred)
matrix = confusion_matrix(y_test , y_pred)

In [8]:
print('Score : ' , score)
print('Classification Report : \n' , classification)
print('Matrix : \n' , matrix)

Score :  0.7866666666666666
Classification Report :
               precision    recall  f1-score   support

           0       0.91      0.78      0.84       105
           1       0.73      0.74      0.73        97
           2       0.74      0.84      0.78        98

    accuracy                           0.79       300
   macro avg       0.79      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300

Matrix :
 [[82 17  6]
 [ 2 72 23]
 [ 6 10 82]]

In [9]:
# Hypermarameter Tuning Yapalım :

In [10]:
model = LogisticRegression()

In [11]:
penalty = ['l1' , 'l2' , 'elasticnet']
c_values = [100 , 10 , 0 , 0.1 , 0.01]
solver =  ['lbfgs' , 'liblinear' , 'newton-cg' , 'newton-cholesky' , 'sag' , 'saga']
params = dict(penalty = penalty , C = c_values , solver = solver)

In [12]:
from sklearn.model_selection import GridSearchCV , StratifiedKFold

In [13]:
cv = StratifiedKFold(n_splits = 5 )

In [14]:
grid = GridSearchCV(estimator = model , param_grid = params , cv = cv , n_jobs = -1)

In [15]:
grid.fit(X_train , y_train)

C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
290 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cg supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver sag supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 71, in _check_solver
    raise ValueError(
        f"Only 'saga' solver supports elasticnet penalty, got solver={solver}."
    )
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver sag supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1203, in fit
    raise ValueError("l1_ratio must be specified when penalty is elasticnet.")
ValueError: l1_ratio must be specified when penalty is elasticnet.

--------------------------------------------------------------------------------
90 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'C' parameter of LogisticRegression must be a float in the range (0.0, inf]. Got 0 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.79428571        nan        nan        nan 0.79
 0.79       0.79428571 0.79       0.79       0.79       0.79
        nan        nan        nan        nan        nan        nan
        nan 0.79428571        nan        nan        nan 0.79
 0.79       0.79428571 0.79       0.79       0.79       0.79
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan 0.79857143        nan        nan        nan 0.79142857
 0.79428571 0.79142857 0.79428571 0.79428571 0.79428571 0.79428571
        nan        nan        nan        nan        nan        nan
        nan 0.77714286        nan        nan        nan 0.79285714
 0.79142857 0.78714286 0.79142857 0.79142857 0.79142857 0.79142857
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']})

In [16]:
y_pred = grid.predict(X_test)

score = accuracy_score(y_test , y_pred) 
classification = classification_report(y_test , y_pred)
matrix = confusion_matrix(y_test , y_pred)

print('Score : ' , score)
print('Classification Report : \n' , classification)
print('Matrix : \n' , matrix)

# Sadece bazı skorlar biraz iyileşti ve conf matrix bir tık değişti ancak yeterli olmadı

Score :  0.7866666666666666
Classification Report :
               precision    recall  f1-score   support

           0       0.92      0.78      0.85       105
           1       0.75      0.71      0.73        97
           2       0.71      0.87      0.78        98

    accuracy                           0.79       300
   macro avg       0.80      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300

Matrix :
 [[82 15  8]
 [ 2 69 26]
 [ 5  8 85]]

In [17]:
# One vs One  ----- One vs Rest deneyelim

In [18]:
from  sklearn.multiclass import OneVsOneClassifier , OneVsRestClassifier

In [19]:
model_for_multiclass = LogisticRegression()

In [20]:
onevsoneclass = OneVsOneClassifier(estimator = model_for_multiclass , n_jobs = -1)
onevsrestclass = OneVsRestClassifier(estimator = model_for_multiclass , n_jobs = -1)

In [21]:
# One vs One

onevsoneclass.fit(X_train , y_train)
y_pred = onevsoneclass.predict(X_test)

score = accuracy_score(y_test , y_pred)
matrix = confusion_matrix(y_test , y_pred)
classification = classification_report(y_test , y_pred)

print('Score : ' , score)
print('Classification Report : \n' , classification)
print('Matrix : \n' , matrix)

Score :  0.7966666666666666
Classification Report :
               precision    recall  f1-score   support

           0       0.92      0.80      0.86       105
           1       0.76      0.74      0.75        97
           2       0.73      0.85      0.78        98

    accuracy                           0.80       300
   macro avg       0.80      0.80      0.80       300
weighted avg       0.81      0.80      0.80       300

Matrix :
 [[84 12  9]
 [ 3 72 22]
 [ 4 11 83]]

In [22]:
# One vs Rest

onevsrestclass.fit(X_train , y_train)
y_pred = onevsrestclass.predict(X_test)

score = accuracy_score(y_test , y_pred)
matrix = confusion_matrix(y_test , y_pred)
classification = classification_report(y_test , y_pred)

print('Score : ' , score)
print('Classification Report : \n' , classification)
print('Matrix : \n' , matrix)

Score :  0.7833333333333333
Classification Report :
               precision    recall  f1-score   support

           0       0.91      0.79      0.85       105
           1       0.73      0.71      0.72        97
           2       0.72      0.85      0.78        98

    accuracy                           0.78       300
   macro avg       0.79      0.78      0.78       300
weighted avg       0.79      0.78      0.78       300

Matrix :
 [[83 16  6]
 [ 2 69 26]
 [ 6  9 83]]