In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('8.1-)adult.csv')

In [3]:
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [5]:
df[df == '?' ] = np.nan

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      30718 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  31978 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [7]:
df = df.dropna()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 1 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30162 non-null  int64
 1   workclass       30162 non-null  object
 2   fnlwgt          30162 non-null  int64
 3   education       30162 non-null  object
 4   education.num   30162 non-null  int64
 5   marital.status  30162 non-null  object
 6   occupation      30162 non-null  object
 7   relationship    30162 non-null  object
 8   race            30162 non-null  object
 9   sex             30162 non-null  object
 10  capital.gain    30162 non-null  int64
 11  capital.loss    30162 non-null  int64
 12  hours.per.week  30162 non-null  int64
 13  native.country  30162 non-null  object
 14  income          30162 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [9]:
df['workclass'].unique()

array(['Private', 'State-gov', 'Federal-gov', 'Self-emp-not-inc',
       'Self-emp-inc', 'Local-gov', 'Without-pay'], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
encoder = LabelEncoder()
df['workclass'] = encoder.fit_transform(df['workclass'])

In [12]:
df['workclass'] = df['workclass'].astype(int)

In [13]:
import warnings
warnings.filterwarnings('ignore')

In [14]:
df['education'].unique()

array(['HS-grad', '7th-8th', 'Some-college', '10th', 'Doctorate',
       'Prof-school', 'Bachelors', 'Masters', '11th', 'Assoc-voc',
       '1st-4th', '5th-6th', 'Assoc-acdm', '12th', '9th', 'Preschool'],
      dtype=object)

In [15]:
edu_map = {
    'Preschool': 'Primary',
    '1st-4th': 'Primary',
    '5th-6th': 'Primary',
    '7th-8th': 'Middle',
    '9th': 'High-school',
    '10th': 'High-school',
    '11th': 'High-school',
    '12th': 'High-school',
    'HS-grad': 'High-school',
    'Some-college': 'College',
    'Assoc-voc': 'College',
    'Assoc-acdm': 'College',
    'Bachelors': 'Bachelors',
    'Masters': 'Masters',
    'Doctorate': 'Doctorate',
    'Prof-school': 'Professional'
}

df['education'] = df['education'].map(edu_map)
df['education'].unique()

array(['High-school', 'Middle', 'College', 'Doctorate', 'Professional',
       'Bachelors', 'Masters', 'Primary'], dtype=object)

In [16]:
df.drop(axis = 1 , columns = ['education.num'] ,inplace = True)

In [17]:
df['marital.status'] = encoder.fit_transform(df['marital.status'] )

In [18]:
"""from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[['High School', "Bachelor's", "Master's"]])
df['Education_Encoded'] = encoder.fit_transform(df[['Education']])"""

'from sklearn.preprocessing import OrdinalEncoder\nencoder = OrdinalEncoder(categories=[[\'High School\', "Bachelor\'s", "Master\'s"]])\ndf[\'Education_Encoded\'] = encoder.fit_transform(df[[\'Education\']])'

In [19]:
from sklearn.preprocessing import OrdinalEncoder
education_order = [['Primary', 'Middle', 'High-school', 'College', 'Bachelors', 'Masters', 'Professional', 'Doctorate']]

ord_encoder = OrdinalEncoder(categories=education_order)

df['education'] = ord_encoder.fit_transform(df[['education']])
df.head()

,age,workclass,fnlwgt,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
1,82,2,132870,2.0,6,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
3,54,2,140359,1.0,0,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,2,264663,3.0,5,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
5,34,2,216864,2.0,0,Other-service,Unmarried,White,Female,0,3770,45,United-States,<=50K
6,38,2,150601,2.0,5,Adm-clerical,Unmarried,White,Male,0,3770,40,United-States,<=50K

In [20]:
df['education'] = df['education'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 1 to 32560
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30162 non-null  int64
 1   workclass       30162 non-null  int64
 2   fnlwgt          30162 non-null  int64
 3   education       30162 non-null  int64
 4   marital.status  30162 non-null  int64
 5   occupation      30162 non-null  object
 6   relationship    30162 non-null  object
 7   race            30162 non-null  object
 8   sex             30162 non-null  object
 9   capital.gain    30162 non-null  int64
 10  capital.loss    30162 non-null  int64
 11  hours.per.week  30162 non-null  int64
 12  native.country  30162 non-null  object
 13  income          30162 non-null  object
dtypes: int64(8), object(6)
memory usage: 3.5+ MB

In [21]:
df['occupation'] = encoder.fit_transform(df['occupation'])
df['occupation'] = df['occupation'].astype(int)

In [22]:
df['relationship'] = encoder.fit_transform(df['relationship'])
df['relationship'] = df['relationship'].astype(int)

In [23]:
df['race'] = encoder.fit_transform(df['race'])
df['race'] = df['race'].astype(int)

In [24]:
df['sex'].unique()

array(['Female', 'Male'], dtype=object)

In [25]:
ord_encoder = OrdinalEncoder(categories =[['Female' , 'Male']])
df['sex'] = ord_encoder.fit_transform(df[['sex']])
df['sex'] = df['sex'].astype(int)

In [26]:
df.drop(axis = 1 , columns = ['native.country'] , inplace = True)

In [27]:
df['income'] = df['income'].str.replace('<=50K' , '0')
df['income'] = df['income'].str.replace('>50K' ,  '1')

In [28]:
df['income'] = df['income'].astype(int)

In [29]:
df.head()

,age,workclass,fnlwgt,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,income
1,82,2,132870,2,6,3,1,4,0,0,4356,18,0
3,54,2,140359,1,0,6,4,4,0,0,3900,40,0
4,41,2,264663,3,5,9,3,4,0,0,3900,40,0
5,34,2,216864,2,0,7,4,4,0,0,3770,45,0
6,38,2,150601,2,5,0,4,4,1,0,3770,40,0

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 1 to 32560
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30162 non-null  int64
 1   workclass       30162 non-null  int64
 2   fnlwgt          30162 non-null  int64
 3   education       30162 non-null  int64
 4   marital.status  30162 non-null  int64
 5   occupation      30162 non-null  int64
 6   relationship    30162 non-null  int64
 7   race            30162 non-null  int64
 8   sex             30162 non-null  int64
 9   capital.gain    30162 non-null  int64
 10  capital.loss    30162 non-null  int64
 11  hours.per.week  30162 non-null  int64
 12  income          30162 non-null  int64
dtypes: int64(13)
memory usage: 3.2 MB

In [31]:
df.drop(columns=['fnlwgt'], inplace=True)

In [32]:
df['capital.loss'] = df['capital.loss'] / 100

In [33]:
df['capital.loss'] = df['capital.loss'].astype(float)

In [34]:
df['capital.gain'] = df['capital.gain'] / 100 
df['capital.gain']  = df['capital.gain'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 1 to 32560
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30162 non-null  int64
 1   workclass       30162 non-null  int64
 2   education       30162 non-null  int64
 3   marital.status  30162 non-null  int64
 4   occupation      30162 non-null  int64
 5   relationship    30162 non-null  int64
 6   race            30162 non-null  int64
 7   sex             30162 non-null  int64
 8   capital.gain    30162 non-null  float64
 9   capital.loss    30162 non-null  float64
 10  hours.per.week  30162 non-null  int64
 11  income          30162 non-null  int64
dtypes: float64(2), int64(10)
memory usage: 3.0 MB

In [35]:
df['income'].value_counts()

income
0    22654
1     7508
Name: count, dtype: int64

In [36]:
# READY FOR MACHINE LEARNING

In [37]:
from sklearn.model_selection import GridSearchCV , train_test_split , StratifiedKFold
from sklearn.metrics import accuracy_score , confusion_matrix , auc , roc_auc_score , classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [38]:
scaler = StandardScaler()

In [39]:
X = df.drop(columns = 'income' , axis = 1)
y = df['income']

X_train , X_test , y_train , y_test = train_test_split(X , y ,test_size = 0.3 , random_state = 15)

In [40]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [41]:
# Logistic - Regression

In [42]:
regression = LogisticRegression()
regression.fit(X_train , y_train)

LogisticRegression()

In [43]:
y_pred = regression.predict(X_test)

In [44]:
score = accuracy_score(y_test , y_pred)
matrix = confusion_matrix(y_test , y_pred)
classification = classification_report(y_test , y_pred)

print('Score  :  ' , score)
print('Classification Report : \n' , classification)
print('Confusion Matrix : \n' , matrix)

Score  :   0.8217482594761852
Classification Report :
               precision    recall  f1-score   support

           0       0.84      0.94      0.89      6818
           1       0.72      0.45      0.55      2231

    accuracy                           0.82      9049
   macro avg       0.78      0.70      0.72      9049
weighted avg       0.81      0.82      0.81      9049

Confusion Matrix :
 [[6436  382]
 [1231 1000]]

In [45]:
# Paramether :

In [46]:
cv = StratifiedKFold(n_splits = 5 )
model = LogisticRegression()

In [47]:
penalty = ['l1' , 'l2' , 'elasticnet']
c_values = [100 , 10 , 5 , 0.1 , 0.01]
solver = ['sag' , 'saga' , 'lbfgs' , 'newton-cg' , 'liblinear' , 'newton-cholesky']
class_weight = [{0 : w , 1 : y} for w in [100 , 50 , 10 , 5 , 1] for y in  [100 , 50 , 10 , 5 , 1]]
params = dict(penalty = penalty , C = c_values , solver = solver , class_weight = class_weight)
grid = GridSearchCV(estimator = model , param_grid = params , scoring = 'accuracy' , cv = cv , n_jobs = -1)

In [48]:
# ------------------ SMOTE KULLANIMI ----------------

In [49]:
y.value_counts() # Dengesiz Veri Seti

income
0    22654
1     7508
Name: count, dtype: int64

In [57]:
from imblearn.over_sampling import SMOTE
X_train , X_test , y_train , y_test = train_test_split(X , y , random_state = 20 , test_size = 0.3)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled =  scaler.transform(X_test)

smote = SMOTE(random_state = 20)
X_train_resampled , y_train_resampled = smote.fit_resample(X_train_scaled , y_train)

model = LogisticRegression()
cv = StratifiedKFold(n_splits = 7)

params = dict(penalty = ['l1' , 'l2' , 'elasticnet'],
              C = [20 , 10 , 0 , 0.1],
              solver = ['sag' , 'saga' , 'newton-cg' , 'newton-cholesky' , 'lbfgs' , 'liblinear'],
              l1_ratio = [0.25 , 0.5 , 0.75],
             )
grid = GridSearchCV(estimator = model , param_grid = params , n_jobs = -1 , cv = cv , scoring = 'f1_macro')

In [58]:
grid.fit(X_train_resampled , y_train_resampled)

GridSearchCV(cv=StratifiedKFold(n_splits=7, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [20, 10, 0, 0.1], 'l1_ratio': [0.25, 0.5, 0.75],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['sag', 'saga', 'newton-cg',
                                    'newton-cholesky', 'lbfgs', 'liblinear']},
             scoring='f1_macro')

In [59]:
y_pred = grid.predict(X_test_scaled)

print('Classification Report  : \n' , classification_report(y_test , y_pred))
print('Confusion Matrix : \n' , confusion_matrix(y_test , y_pred))
print('Accuracy Score : \n' , accuracy_score(y_test , y_pred))

Classification Report  :
               precision    recall  f1-score   support

           0       0.90      0.77      0.83      6748
           1       0.52      0.76      0.62      2301

    accuracy                           0.76      9049
   macro avg       0.71      0.76      0.72      9049
weighted avg       0.81      0.76      0.78      9049

Confusion Matrix :
 [[5167 1581]
 [ 555 1746]]
Accuracy Score :
 0.7639518178804288